export const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST';
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USERS_DELETE_ERROR = 'USERS_DELETE_ERROR';

export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_ERROR = 'USERS_LOAD_ERROR';

export const USERS_REMOVE_EXPIRATION_REQUEST =
  'USERS_REMOVE_EXPIRATION_REQUEST';
export const USERS_REMOVE_EXPIRATION_SUCCESS =
  'USERS_REMOVE_EXPIRATION_SUCCESS';
export const USERS_REMOVE_EXPIRATION_ERROR = 'USERS_REMOVE_EXPIRATION_ERROR';

export const INVITATION_CREATE_REQUEST = 'INVITATION_CREATE_REQUEST';
export const INVITATION_CREATE_SUCCESS = 'INVITATION_CREATE_SUCCESS';
export const INVITATION_CREATE_ERROR = 'INVITATION_CREATE_ERROR';

export const INVITATIONS_LOAD_REQUEST = 'INVITATIONS_LOAD_REQUEST';
export const INVITATIONS_LOAD_SUCCESS = 'INVITATIONS_LOAD_SUCCESS';
export const INVITATIONS_LOAD_ERROR = 'INVITATIONS_LOAD_ERROR';
