apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: happa-staging
    spec:
      volumes:
        - name: giantswarm-cert
          secret:
            secretName: giantswarm-cert
      containers:
      - name: happa-staging
        image: quay.io/giantswarm/happa:{{ .BuildInfo.SHA }}
        volumeMounts:
        - name: giantswarm-cert
          mountPath: /etc/nginx/certs
          readOnly: true
        env:
        - name: PASSAGE_ENDPOINT
          value: {{ .Installation.V1.GiantSwarm.Passage.Address | urlString }}
        - name: API_ENDPOINT
          value: {{ .Installation.V1.GiantSwarm.API.Address | urlString }}
        - name: DESMOTES_ENDPOINT
          value: {{ .Installation.V1.GiantSwarm.Desmotes.Address | urlString }}
        - name: INTERCOM_APP_ID
          value: ictssdcu
        - name: ENVIRONMENT
          value: kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
      imagePullSecrets:
      - name: giantswarm-registry

---

apiVersion: v1
kind: Service
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: happa-staging

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: happa-staging
  namespace: giantswarm
  labels:
    app: happa-staging
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: happa-staging.giantswarm.io
    http:
      paths:
      - backend:
          serviceName: happa-staging
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - happa-staging.giantswarm.io
