apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ tpl .Values.resource.default.name  . }}-pull-secret
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    app: happa
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
