name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Added'
    label: 'kind/feature'

  - title: 'Changed'
    labels:
      - 'kind/change'
      - 'kind/ux-enhancement'

  - title: 'Deprecated'
    label: 'kind/deprecation'

  - title: 'Removed'
    label: 'kind/removal'

  - title: 'Fixed'
    label: 'kind/bug'

  - title: 'Security'
    label: 'kind/security'

exclude-labels:
  - 'dependencies'
  - 'kind/dev-change'
  - 'kind/refactor'

change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
