export const CLUSTER_NODEPOOLS_LOAD_REQUEST = 'CLUSTER_NODEPOOLS_LOAD_REQUEST';
export const CLUSTER_NODEPOOLS_LOAD_SUCCESS = 'CLUSTER_NODEPOOLS_LOAD_SUCCESS';
export const CLUSTER_NODEPOOLS_LOAD_ERROR = 'CLUSTER_NODEPOOLS_LOAD_ERROR';

export const NODEPOOL_MULTIPLE_LOAD_REQUEST = 'NODEPOOL_MULTIPLE_LOAD_REQUEST';
export const NODEPOOL_MULTIPLE_LOAD_FINISHED =
  'NODEPOOL_MULTIPLE_LOAD_FINISHED';
export const NODEPOOL_MULTIPLE_CREATE_REQUEST =
  'NODEPOOL_MULTIPLE_CREATE_REQUEST';
export const NODEPOOL_MULTIPLE_CREATE_FINISHED =
  'NODEPOOL_MULTIPLE_CREATE_FINISHED';
export const NODEPOOL_PATCH = 'NODEPOOL_PATCH';
export const NODEPOOL_PATCH_ERROR = 'NODEPOOL_PATCH_ERROR';
export const NODEPOOL_DELETE = 'NODEPOOL_DELETE';
export const NODEPOOL_DELETE_CONFIRMED_REQUEST =
  'NODEPOOL_DELETE_CONFIRMED_REQUEST';
export const NODEPOOL_DELETE_SUCCESS = 'NODEPOOL_DELETE_SUCCESS';
export const NODEPOOL_DELETE_ERROR = 'NODEPOOL_DELETE_ERROR';
export const NODEPOOL_CREATE_REQUEST = 'NODEPOOL_CREATE_REQUEST';
export const NODEPOOL_CREATE_SUCCESS = 'NODEPOOL_CREATE_SUCCESS';
export const NODEPOOL_CREATE_ERROR = 'NODEPOOL_CREATE_ERROR';
