# This Dockerfile is optimized for the use in local development,
# to build and run a NodeJS container through docker-compose.
#
# Main goals are:
#
# - src folder gets mounted, so webpack dev server picks up changes
#   and re-builds automatically
#
# - relatively short statup time, at least as long as dependencies
#   have not changed.
# 
# - persist dependencies in use to yarn.lock file, so we can use the
#   exact same versions in CI builds.

FROM quay.io/giantswarm/happa-build:latest

EXPOSE 7000

RUN npm set progress=false
RUN npm config set registry https://registry.npmjs.org/

# Install some slow dependencies individually, so they can get cached as layers
RUN yarn add node-sass@4.9.4

# Install app dependencies
COPY package.json /usr/src/app/
COPY .eslintrc /usr/src/app/
COPY ./Gruntfile.js /usr/src/app/
COPY ./package.json /usr/src/app/
COPY ./webpack.config.js /usr/src/app/
COPY ./webpack.dist.config.js /usr/src/app/

COPY ./dev.sh /usr/src/app/

ENTRYPOINT ["/usr/src/app/dev.sh"]
