FROM mhart/alpine-node:6.2.2

RUN apk update && apk add git g++ curl make python && rm -rf /var/cache/apk/*

RUN curl -Ls https://github.com/fgrehm/docker-phantomjs2/releases/download/v2.0.0-20150722/dockerized-phantomjs.tar.gz \
       | tar xz -C /

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm config set registry https://registry.npmjs.org/
RUN npm set progress=false
RUN npm install
RUN npm install -g grunt
RUN npm install -g npm-check-updates

# Bundle app source
COPY . /usr/src/app

EXPOSE 8000
