/**
 * All our redux action types are defined here.
 *
 * Action type names usually follow some conventions.
 *
 * User transactions like deleting a cluster usually involve several action types
 * named using a common prefix. Example:
 *
 *   'CLUSTER_DELETE'
 *      Invoked when the user expressed the intend to delete a cluster.
 *      This is e. g. used to reveal a confirmation dialog.
 *
 *   'CLUSTER_DELETE_CONFIRMED'
 *      The user has confirmed the intent to delete a cluster.
 *      This should lead to the actual API call deleting the cluster.
 *
 *   'CLUSTER_DELETE_SUCCESS'
 *      The API call to delete the cluster was successful.
 *
 *   'CLUSTER_DELETE_ERROR'
 *      The API call to delete the cluster was not successful.
 *
 * For loading resources we usually use this action name pattern:
 *
 *    '<NOUN>_LOAD'
 *    '<NOUN>_LOAD_SUCCESS'
 *    '<NOUN>_LOAD_ERROR'
 *
 * where NOUN can be either a singular or plural version of the resource name,
 * depending on which fits best.
 *
 * NOUN can also represent the nesting of resources.
 */

// Catalogs - Loading all the catalogs from the k8s api
export const CATALOGS_LOAD = 'CATALOGS_LOAD';
export const CATALOGS_LOAD_SUCCESS = 'CATALOGS_LOAD_SUCCESS';
export const CATALOGS_LOAD_ERROR = 'CATALOGS_LOAD_ERROR';

// Catalog - Loading an individual catalog's index.yaml
export const CATALOG_LOAD_INDEX = 'CATALOG_LOAD_INDEX';
export const CATALOG_LOAD_INDEX_SUCCESS = 'CATALOG_LOAD_INDEX_SUCCESS';
export const CATALOG_LOAD_INDEX_ERROR = 'CATALOG_LOAD_INDEX_ERROR';

// Cluster Select
// This action is for setting a Cluster ID in the state.
// It is used for example for keeping context when moving from the cluster detail page.
// To the  app catalog.
export const CLUSTER_SELECT = 'CLUSTER_SELECT';

// Clusters
export const CLUSTERS_LIST_REQUEST = 'CLUSTERS_LIST_REQUEST';
export const CLUSTERS_LIST_SUCCESS = 'CLUSTERS_LIST_SUCCESS';
export const CLUSTERS_LIST_ERROR = 'CLUSTERS_LIST_ERROR';

export const CLUSTERS_DETAILS_REQUEST = 'CLUSTERS_DETAILS_REQUEST';
export const CLUSTERS_DETAILS_FINISHED = 'CLUSTERS_DETAILS_FINISHED';

export const CLUSTER_LOAD_DETAILS_REQUEST = 'CLUSTER_LOAD_DETAILS_REQUEST';
export const CLUSTER_LOAD_DETAILS_SUCCESS = 'CLUSTER_LOAD_DETAILS_SUCCESS';
export const CLUSTER_LOAD_DETAILS_ERROR = 'CLUSTER_LOAD_DETAILS_ERROR';

export const CLUSTER_LOAD_STATUS = 'CLUSTER_LOAD_STATUS';
export const CLUSTER_LOAD_STATUS_SUCCESS = 'CLUSTER_LOAD_STATUS_SUCCESS';
export const CLUSTER_LOAD_STATUS_NOT_FOUND = 'CLUSTER_LOAD_STATUS_NOT_FOUND';
export const CLUSTER_LOAD_STATUS_ERROR = 'CLUSTER_LOAD_STATUS_ERROR';

export const CLUSTERS_LOAD = 'CLUSTERS_LOAD';
export const CLUSTERS_LOAD_SUCCESS = 'CLUSTERS_LOAD_SUCCESS';
export const CLUSTERS_LOAD_ERROR = 'CLUSTERS_LOAD_ERROR';

export const CLUSTER_CREATE = 'CLUSTER_CREATE';
export const CLUSTER_CREATE_SUCCESS = 'CLUSTER_CREATE_SUCCESS';
export const V5_CLUSTER_CREATE_SUCCESS = 'V5_CLUSTER_CREATE_SUCCESS';
export const CLUSTER_CREATE_ERROR = 'CLUSTER_CREATE_ERROR';

export const CLUSTER_DELETE = 'CLUSTER_DELETE';
export const CLUSTER_DELETE_CONFIRMED = 'CLUSTER_DELETE_CONFIRMED';
export const CLUSTER_DELETE_SUCCESS = 'CLUSTER_DELETE_SUCCESS';
export const CLUSTER_DELETE_ERROR = 'CLUSTER_DELETE_ERROR';

export const CLUSTER_PATCH = 'CLUSTER_PATCH';
export const CLUSTER_PATCH_ERROR = 'CLUSTER_PATCH_ERROR';

// Clusters - Apps
export const CLUSTER_LOAD_APPS = 'CLUSTER_LOAD_APPS';
export const CLUSTER_LOAD_APPS_SUCCESS = 'CLUSTER_LOAD_APPS_SUCCESS';
export const CLUSTER_LOAD_APPS_ERROR = 'CLUSTER_LOAD_APPS_ERROR';

export const CLUSTER_INSTALL_APP = 'CLUSTER_INSTALL_APP';
export const CLUSTER_INSTALL_APP_SUCCESS = 'CLUSTER_INSTALL_APP_SUCCESS';
export const CLUSTER_INSTALL_APP_ERROR = 'CLUSTER_INSTALL_APP_ERROR';

export const CLUSTER_DELETE_APP = 'CLUSTER_DELETE_APP';
export const CLUSTER_DELETE_APP_SUCCESS = 'CLUSTER_DELETE_APP_SUCCESS';
export const CLUSTER_DELETE_APP_ERROR = 'CLUSTER_DELETE_APP_ERROR';

// Clusters - App Configs
export const CLUSTER_CREATE_APP_CONFIG = 'CLUSTER_CREATE_APP_CONFIG';
export const CLUSTER_CREATE_APP_CONFIG_SUCCESS =
  'CLUSTER_CREATE_APP_CONFIG_SUCCESS';
export const CLUSTER_CREATE_APP_CONFIG_ERROR =
  'CLUSTER_CREATE_APP_CONFIG_ERROR';

export const CLUSTER_UPDATE_APP_CONFIG = 'CLUSTER_UPDATE_APP_CONFIG';
export const CLUSTER_UPDATE_APP_CONFIG_SUCCESS =
  'CLUSTER_UPDATE_APP_CONFIG_SUCCESS';
export const CLUSTER_UPDATE_APP_CONFIG_ERROR =
  'CLUSTER_UPDATE_APP_CONFIG_ERROR';

export const CLUSTER_DELETE_APP_CONFIG = 'CLUSTER_DELETE_APP_CONFIG';
export const CLUSTER_DELETE_APP_CONFIG_SUCCESS =
  'CLUSTER_DELETE_APP_CONFIG_SUCCESS';
export const CLUSTER_DELETE_APP_CONFIG_ERROR =
  'CLUSTER_UPDATE_APP_CONFIG_ERROR';

// Clusters - App Secrets
export const CLUSTER_CREATE_APP_SECRET = 'CLUSTER_CREATE_APP_SECRET';
export const CLUSTER_CREATE_APP_SECRET_SUCCESS =
  'CLUSTER_CREATE_APP_SECRET_SUCCESS';
export const CLUSTER_CREATE_APP_SECRET_ERROR =
  'CLUSTER_CREATE_APP_SECRET_ERROR';

export const CLUSTER_UPDATE_APP_SECRET = 'CLUSTER_UPDATE_APP_SECRET';
export const CLUSTER_UPDATE_APP_SECRET_SUCCESS =
  'CLUSTER_UPDATE_APP_SECRET_SUCCESS';
export const CLUSTER_UPDATE_APP_SECRET_ERROR =
  'CLUSTER_UPDATE_APP_SECRET_ERROR';

export const CLUSTER_DELETE_APP_SECRET = 'CLUSTER_DELETE_APP_SECRET';
export const CLUSTER_DELETE_APP_SECRET_SUCCESS =
  'CLUSTER_DELETE_APP_SECRET_SUCCESS';
export const CLUSTER_DELETE_APP_SECRET_ERROR =
  'CLUSTER_UPDATE_APP_SECRET_ERROR';

// Clusters - Key Pairs
export const CLUSTER_LOAD_KEY_PAIRS = 'CLUSTER_LOAD_KEY_PAIRS';
export const CLUSTER_LOAD_KEY_PAIRS_SUCCESS = 'CLUSTER_LOAD_KEY_PAIRS_SUCCESS';
export const CLUSTER_LOAD_KEY_PAIRS_ERROR = 'CLUSTER_LOAD_KEY_PAIRS_ERROR';

export const CLUSTER_CREATE_KEY_PAIR = 'CLUSTER_CREATE_KEY_PAIR';
export const CLUSTER_CREATE_KEY_PAIR_SUCCESS =
  'CLUSTER_CREATE_KEY_PAIR_SUCCESS';
export const CLUSTER_CREATE_KEY_PAIR_ERROR = 'CLUSTER_CREATE_KEY_PAIR_ERROR';

// Clusters - Node Pools
// TODO Remove
export const CLUSTERS_LOAD_NODEPOOLS_SUCCESS =
  'CLUSTERS_LOAD_NODEPOOLS_SUCCESS';
export const CLUSTERS_LOAD_NODEPOOLS_ERROR = 'CLUSTERS_LOAD_NODEPOOLS_ERROR';

// Node Pools
export const CLUSTER_NODEPOOLS_LOAD_REQUEST = 'CLUSTER_NODEPOOLS_LOAD_REQUEST';
export const CLUSTER_NODEPOOLS_LOAD_SUCCESS = 'CLUSTER_NODEPOOLS_LOAD_SUCCESS';
export const CLUSTER_NODEPOOLS_LOAD_ERROR = 'CLUSTER_NODEPOOLS_LOAD_ERROR';

// All node pools
export const NODEPOOLS_LOAD_REQUEST = 'NODEPOOLS_LOAD_REQUEST';
export const NODEPOOLS_LOAD_FINISHED = 'NODEPOOLS_LOAD_FINISHED';

export const NODEPOOLS_CREATE = 'NODEPOOLS_CREATE';
export const NODEPOOLS_CREATE_SUCCESS = 'NODEPOOLS_CREATE_SUCCESS';
export const NODEPOOLS_CREATE_ERROR = 'NODEPOOLS_CREATE_ERROR';

export const NODEPOOL_PATCH = 'NODEPOOL_PATCH';
export const NODEPOOL_PATCH_ERROR = 'NODEPOOL_PATCH_ERROR';

export const NODEPOOL_DELETE = 'NODEPOOL_DELETE';
export const NODEPOOL_DELETE_CONFIRMED = 'NODEPOOL_DELETE_CONFIRMED';
export const NODEPOOL_DELETE_SUCCESS = 'NODEPOOL_DELETE_SUCCESS';
export const NODEPOOL_DELETE_ERROR = 'NODEPOOL_DELETE_ERROR';

export const NODEPOOL_CREATE_SUCCESS = 'NODEPOOL_CREATE_SUCCESS';
export const NODEPOOL_CREATE_ERROR = 'NODEPOOL_CREATE_ERROR';

// General Errors
export const UNAUTHORIZED = 'UNAUTHORIZED';

// Info
export const INFO_LOAD = 'INFO_LOAD';
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS';
export const INFO_LOAD_ERROR = 'INFO_LOAD_ERROR';

// Invitations
export const INVITATION_CREATE = 'INVITATION_CREATE';
export const INVITATION_CREATE_SUCCESS = 'INVITATION_CREATE_SUCCESS';
export const INVITATION_CREATE_ERROR = 'INVITATION_CREATE_ERROR';

export const INVITATIONS_LOAD = 'INVITATIONS_LOAD';
export const INVITATIONS_LOAD_SUCCESS = 'INVITATIONS_LOAD_SUCCESS';
export const INVITATIONS_LOAD_ERROR = 'INVITATIONS_LOAD_ERROR';

// Modals
export const MODAL_HIDE = 'MODAL_HIDE';

// Organizations
export const ORGANIZATION_SELECT = 'ORGANIZATION_SELECT';

export const ORGANIZATIONS_LOAD = 'ORGANIZATIONS_LOAD';
export const ORGANIZATIONS_LOAD_SUCCESS = 'ORGANIZATIONS_LOAD_SUCCESS';
export const ORGANIZATIONS_LOAD_ERROR = 'ORGANIZATIONS_LOAD_ERROR';

export const ORGANIZATION_DELETE = 'ORGANIZATION_DELETE';
export const ORGANIZATION_DELETE_CONFIRMED = 'ORGANIZATION_DELETE_CONFIRMED';
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS';
export const ORGANIZATION_DELETE_ERROR = 'ORGANIZATION_DELETE_ERROR';

export const ORGANIZATION_CREATE = 'ORGANIZATION_CREATE';
export const ORGANIZATION_CREATE_CONFIRMED = 'ORGANIZATION_CREATE_CONFIRMED';
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS';
export const ORGANIZATION_CREATE_ERROR = 'ORGANIZATION_CREATE_ERROR';

export const ORGANIZATION_CREDENTIALS_LOAD = 'ORGANIZATION_CREDENTIALS_LOAD';
export const ORGANIZATION_CREDENTIALS_LOAD_SUCCESS =
  'ORGANIZATION_CREDENTIALS_LOAD_SUCCESS';
export const ORGANIZATION_CREDENTIALS_LOAD_ERROR =
  'ORGANIZATION_CREDENTIALS_LOAD_ERROR';

// user intends to set the credentials, so reveal the form
export const ORGANIZATION_CREDENTIALS_SET = 'ORGANIZATION_CREDENTIALS_SET';

// user has submitted the form
export const ORGANIZATION_CREDENTIALS_SET_CONFIRMED =
  'ORGANIZATION_CREDENTIALS_SET_CONFIRMED';

export const ORGANIZATION_CREDENTIALS_SET_SUCCESS =
  'ORGANIZATION_CREDENTIALS_SET_SUCCESS';
export const ORGANIZATION_CREDENTIALS_SET_ERROR =
  'ORGANIZATION_CREDENTIALS_SET_ERROR';

// Organizations - Add / Remove members
export const ORGANIZATION_ADD_MEMBER = 'ORGANIZATION_ADD_MEMBER';
export const ORGANIZATION_ADD_MEMBER_CONFIRMED =
  'ORGANIZATION_ADD_MEMBER_CONFIRMED';
export const ORGANIZATION_ADD_MEMBER_TYPING = 'ORGANIZATION_ADD_MEMBER_TYPING';
export const ORGANIZATION_ADD_MEMBER_SUCCESS =
  'ORGANIZATION_ADD_MEMBER_SUCCESS';
export const ORGANIZATION_ADD_MEMBER_ERROR = 'ORGANIZATION_ADD_MEMBER_ERROR';

export const ORGANIZATION_REMOVE_MEMBER = 'ORGANIZATION_REMOVE_MEMBER';
export const ORGANIZATION_REMOVE_MEMBER_CONFIRMED =
  'ORGANIZATION_REMOVE_MEMBER_CONFIRMED';
export const ORGANIZATION_REMOVE_MEMBER_SUCCESS =
  'ORGANIZATION_REMOVE_MEMBER_SUCCESS';
export const ORGANIZATION_REMOVE_MEMBER_ERROR =
  'ORGANIZATION_REMOVE_MEMBER_ERROR';

// Password Recovery
export const REQUEST_PASSWORD_RECOVERY_TOKEN =
  'REQUEST_PASSWORD_RECOVERY_TOKEN';
export const VERIFY_PASSWORD_RECOVERY_TOKEN = 'VERIFY_PASSWORD_RECOVERY_TOKEN';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';

// User related
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const REFRESH_USER_INFO_SUCCESS = 'REFRESH_USER_INFO_SUCCESS';
export const REFRESH_USER_INFO_ERROR = 'REFRESH_USER_INFO_ERROR';

export const USERS_DELETE = 'USERS_DELETE';
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USERS_DELETE_ERROR = 'USERS_DELETE_ERROR';

export const USERS_LOAD = 'USERS_LOAD';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_ERROR = 'USERS_LOAD_ERROR';

export const USERS_REMOVE_EXPIRATION = 'USERS_REMOVE_EXPIRATION';
export const USERS_REMOVE_EXPIRATION_SUCCESS =
  'USERS_REMOVE_EXPIRATION_SUCCESS';
export const USERS_REMOVE_EXPIRATION_ERROR = 'USERS_REMOVE_EXPIRATION_ERROR';

// Releases
export const RELEASES_LOAD = 'RELEASES_LOAD';
export const RELEASES_LOAD_SUCCESS = 'RELEASES_LOAD_SUCCESS';
export const RELEASES_LOAD_ERROR = 'RELEASES_LOAD_ERROR';

export const RELEASE_SELECTED = 'RELEASE_SELECTED';
