apiVersion: v1
kind: ConfigMap
metadata:
  name: happa-service-migration-configmap
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: happa-service-migration
data:
  config.yaml: |
    service:
      delete:
        resources:
          resourceFile: "/var/run/happa-service-migration/configmap/resources.json"
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
  resources.json: |
    [
        {
            "kind": "Service",
            "name": "happa",
            "namespace": "giantswarm",
            "matchLabels": {
                "app": "happa"
            },
            "excludeLabels": {
            }
        }
    ]
