apiVersion: v1
kind: ServiceAccount
metadata:
  name: happa-service-migration
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  namespace: {{ .Values.namespace }}
  labels:
    app: happa-service-migration
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: happa-service-migration
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: happa-service-migration
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - "get"
  - "delete"
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - happa-psp
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: happa-service-migration 
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: happa-service-migration
subjects:
  - kind: ServiceAccount
    name: happa-service-migration
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: happa-service-migration
  apiGroup: rbac.authorization.k8s.io
