apiVersion: batch/v1
kind: Job
metadata:
  name: happa-service-migration
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: happa-service-migration
spec:
  template:
    spec:
      volumes:
      - name: happa-service-migration-configmap
        configMap:
          name: happa-service-migration-configmap
          items:
          - key: config.yaml
            path: config.yaml
          - key: resources.json
            path: resources.json
      serviceAccountName: happa-service-migration
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: happa-service-migration
        image: quay.io/giantswarm/k8s-migrator:latest
        volumeMounts:
        - name: happa-service-migration-configmap
          mountPath: /var/run/happa-service-migration/configmap/
        args:
        - delete
        - --config.dirs=/var/run/happa-service-migration/configmap/
        - --config.files=config
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        restartPolicy: Never
  backoffLimit: 4
