apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: happa-certs-secret
  namespace: giantswarm
data:
  ca.pem: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CAPem | b64enc | quote }}
  crt.pem: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  key.pem: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
