export const ORGANIZATION_SELECT = 'ORGANIZATION_SELECT';
export const ORGANIZATION_LOAD_MAPI_REQUEST = 'ORGANIZATION_LOAD_MAPI_REQUEST';
export const ORGANIZATION_LOAD_REQUEST = 'ORGANIZATION_LOAD_REQUEST';
export const ORGANIZATION_LOAD_SUCCESS = 'ORGANIZATION_LOAD_SUCCESS';
export const ORGANIZATION_LOAD_ERROR = 'ORGANIZATION_LOAD_ERROR';
export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST';
export const ORGANIZATION_DELETE_CONFIRMED = 'ORGANIZATION_DELETE_CONFIRMED';
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS';
export const ORGANIZATION_DELETE_ERROR = 'ORGANIZATION_DELETE_ERROR';
export const ORGANIZATION_CREATE_REQUEST = 'ORGANIZATION_CREATE_REQUEST';
export const ORGANIZATION_CREATE_CONFIRMED = 'ORGANIZATION_CREATE_CONFIRMED';
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS';
export const ORGANIZATION_CREATE_ERROR = 'ORGANIZATION_CREATE_ERROR';
export const ORGANIZATION_CREDENTIALS_LOAD_REQUEST =
  'ORGANIZATION_CREDENTIALS_LOAD_REQUEST';
export const ORGANIZATION_CREDENTIALS_LOAD_SUCCESS =
  'ORGANIZATION_CREDENTIALS_LOAD_SUCCESS';
export const ORGANIZATION_CREDENTIALS_LOAD_ERROR =
  'ORGANIZATION_CREDENTIALS_LOAD_ERROR';
export const ORGANIZATION_CREDENTIALS_SET = 'ORGANIZATION_CREDENTIALS_SET';
export const ORGANIZATION_CREDENTIALS_SET_CONFIRMED_REQUEST =
  'ORGANIZATION_CREDENTIALS_SET_CONFIRMED_REQUEST';
export const ORGANIZATION_CREDENTIALS_SET_SUCCESS =
  'ORGANIZATION_CREDENTIALS_SET_SUCCESS';
export const ORGANIZATION_CREDENTIALS_SET_ERROR =
  'ORGANIZATION_CREDENTIALS_SET_ERROR';
export const ORGANIZATION_CREDENTIALS_SET_DISCARD =
  'ORGANIZATION_CREDENTIALS_SET_DISCARD';
export const ORGANIZATION_ADD_MEMBER_REQUEST =
  'ORGANIZATION_ADD_MEMBER_REQUEST';
export const ORGANIZATION_ADD_MEMBER_CONFIRMED =
  'ORGANIZATION_ADD_MEMBER_CONFIRMED';
export const ORGANIZATION_ADD_MEMBER_SUCCESS =
  'ORGANIZATION_ADD_MEMBER_SUCCESS';
export const ORGANIZATION_ADD_MEMBER_ERROR = 'ORGANIZATION_ADD_MEMBER_ERROR';
export const ORGANIZATION_REMOVE_MEMBER = 'ORGANIZATION_REMOVE_MEMBER';
export const ORGANIZATION_REMOVE_MEMBER_CONFIRMED_REQUEST =
  'ORGANIZATION_REMOVE_MEMBER_CONFIRMED_REQUEST';
export const ORGANIZATION_REMOVE_MEMBER_SUCCESS =
  'ORGANIZATION_REMOVE_MEMBER_SUCCESS';
export const ORGANIZATION_REMOVE_MEMBER_ERROR =
  'ORGANIZATION_REMOVE_MEMBER_ERROR';
