export const CLUSTERS_LIST_REQUEST = 'CLUSTERS_LIST_REQUEST';
export const CLUSTERS_LIST_SUCCESS = 'CLUSTERS_LIST_SUCCESS';
export const CLUSTERS_LIST_ERROR = 'CLUSTERS_LIST_ERROR';

export const CLUSTERS_LIST_REFRESH_REQUEST = 'CLUSTERS_LIST_REFRESH_REQUEST';
export const CLUSTERS_LIST_REFRESH_SUCCESS = 'CLUSTERS_LIST_REFRESH_SUCCESS';
export const CLUSTERS_LIST_REFRESH_ERROR = 'CLUSTERS_LIST_REFRESH_ERROR';

export const CLUSTERS_DETAILS_REQUEST = 'CLUSTERS_DETAILS_REQUEST';
export const CLUSTERS_DETAILS_FINISHED = 'CLUSTERS_DETAILS_FINISHED';

export const CLUSTER_LOAD_DETAILS_REQUEST = 'CLUSTER_LOAD_DETAILS_REQUEST';
export const CLUSTER_LOAD_DETAILS_SUCCESS = 'CLUSTER_LOAD_DETAILS_SUCCESS';
export const CLUSTER_LOAD_DETAILS_ERROR = 'CLUSTER_LOAD_DETAILS_ERROR';

export const CLUSTER_LOAD_STATUS_REQUEST = 'CLUSTER_LOAD_STATUS_REQUEST';
export const CLUSTER_LOAD_STATUS_SUCCESS = 'CLUSTER_LOAD_STATUS_SUCCESS';
export const CLUSTER_LOAD_STATUS_NOT_FOUND = 'CLUSTER_LOAD_STATUS_NOT_FOUND';
export const CLUSTER_LOAD_STATUS_ERROR = 'CLUSTER_LOAD_STATUS_ERROR';

export const CLUSTER_CREATE_REQUEST = 'CLUSTER_CREATE_REQUEST';
export const CLUSTER_CREATE_SUCCESS = 'CLUSTER_CREATE_SUCCESS';
export const V5_CLUSTER_CREATE_SUCCESS = 'V5_CLUSTER_CREATE_SUCCESS';
export const CLUSTER_CREATE_ERROR = 'CLUSTER_CREATE_ERROR';

export const BATCHED_CLUSTER_CREATION_REQUEST =
  'BATCHED_CLUSTER_CREATION_REQUEST';
export const BATCHED_CLUSTER_CREATION_SUCCESS =
  'BATCHED_CLUSTER_CREATION_SUCCESS';
export const BATCHED_CLUSTER_CREATION_ERROR = 'BATCHED_CLUSTER_CREATION_ERROR';

export const CLUSTER_DELETE_REQUEST = 'CLUSTER_DELETE_REQUEST';
export const CLUSTER_DELETE_SUCCESS = 'CLUSTER_DELETE_SUCCESS';
export const CLUSTER_DELETE_ERROR = 'CLUSTER_DELETE_ERROR';
export const CLUSTER_REMOVE_FROM_STORE = 'CLUSTER_REMOVE_FROM_STORE';

export const CLUSTER_PATCH = 'CLUSTER_PATCH';
export const CLUSTER_PATCH_ERROR = 'CLUSTER_PATCH_ERROR';

export const CLUSTER_LOAD_KEY_PAIRS_REQUEST = 'CLUSTER_LOAD_KEY_PAIRS_REQUEST';
export const CLUSTER_LOAD_KEY_PAIRS_SUCCESS = 'CLUSTER_LOAD_KEY_PAIRS_SUCCESS';
export const CLUSTER_LOAD_KEY_PAIRS_ERROR = 'CLUSTER_LOAD_KEY_PAIRS_ERROR';

export const CLUSTER_CREATE_KEY_PAIR_REQUEST =
  'CLUSTER_CREATE_KEY_PAIR_REQUEST';
export const CLUSTER_CREATE_KEY_PAIR_SUCCESS =
  'CLUSTER_CREATE_KEY_PAIR_SUCCESS';
export const CLUSTER_CREATE_KEY_PAIR_ERROR = 'CLUSTER_CREATE_KEY_PAIR_ERROR';
