export const CPAUTH_USER_LOAD = 'CPAUTH_USER_LOAD';
export const CPAUTH_USER_LOAD_REQUEST = 'CPAUTH_USER_LOAD_REQUEST';
export const CPAUTH_USER_LOAD_ERROR = 'CPAUTH_USER_LOAD_ERROR';
export const CPAUTH_USER_LOAD_SUCCESS = 'CPAUTH_USER_LOAD_SUCCESS';
export const CPAUTH_USER_EXPIRED = 'CPAUTH_USER_EXPIRED';
export const CPAUTH_USER_EXPIRING = 'CPAUTH_USER_EXPIRING';
export const CPAUTH_USER_SIGNED_OUT = 'CPAUTH_USER_SIGNED_OUT';
export const CPAUTH_USER_SESSION_TERMINATED = 'CPAUTH_USER_SESSION_TERMINATED';
