export const CATALOGS_LOAD_REQUEST = 'CATALOGS_LOAD_REQUEST';
export const CATALOGS_LOAD_SUCCESS = 'CATALOGS_LOAD_SUCCESS';
export const CATALOGS_LOAD_ERROR = 'CATALOGS_LOAD_ERROR';

export const CATALOGS_LIST = 'CATALOGS_LIST';
export const CATALOGS_LIST_REQUEST = 'CATALOGS_LIST_REQUEST';
export const CATALOGS_LIST_SUCCESS = 'CATALOGS_LIST_SUCCESS';
export const CATALOGS_LIST_ERROR = 'CATALOGS_LIST_ERROR';

export const INSTALL_INGRESS_APP = 'INSTALL_INGRESS_APP';
export const INSTALL_INGRESS_APP_REQUEST = 'INSTALL_INGRESS_APP_REQUEST';
export const INSTALL_INGRESS_APP_SUCCESS = 'INSTALL_INGRESS_APP_SUCCESS';
export const INSTALL_INGRESS_APP_ERROR = 'INSTALL_INGRESS_APP_ERROR';

export const PREPARE_INGRESS_TAB_DATA = 'PREPARE_INGRESS_TAB_DATA';
export const PREPARE_INGRESS_TAB_DATA_REQUEST =
  'PREPARE_INGRESS_TAB_DATA_REQUEST';
export const PREPARE_INGRESS_TAB_DATA_SUCCESS =
  'PREPARE_INGRESS_TAB_DATA_SUCCESS';
export const PREPARE_INGRESS_TAB_DATA_ERROR = 'PREPARE_INGRESS_TAB_DATA_ERROR';

export const CATALOG_LOAD_INDEX_REQUEST = 'CATALOG_LOAD_INDEX_REQUEST';
export const CATALOG_LOAD_INDEX_SUCCESS = 'CATALOG_LOAD_INDEX_SUCCESS';
export const CATALOG_LOAD_INDEX_ERROR = 'CATALOG_LOAD_INDEX_ERROR';
