export const CATALOGS_LOAD_REQUEST = 'CATALOGS_LOAD_REQUEST';
export const CATALOGS_LOAD_SUCCESS = 'CATALOGS_LOAD_SUCCESS';
export const CATALOGS_LOAD_ERROR = 'CATALOGS_LOAD_ERROR';

export const CATALOGS_LIST = 'CATALOGS_LIST';
export const CATALOGS_LIST_REQUEST = 'CATALOGS_LIST_REQUEST';
export const CATALOGS_LIST_SUCCESS = 'CATALOGS_LIST_SUCCESS';
export const CATALOGS_LIST_ERROR = 'CATALOGS_LIST_ERROR';

export const INSTALL_INGRESS_APP = 'INSTALL_INGRESS_APP';
export const INSTALL_INGRESS_APP_REQUEST = 'INSTALL_INGRESS_APP_REQUEST';
export const INSTALL_INGRESS_APP_SUCCESS = 'INSTALL_INGRESS_APP_SUCCESS';
export const INSTALL_INGRESS_APP_ERROR = 'INSTALL_INGRESS_APP_ERROR';

export const PREPARE_INGRESS_TAB_DATA = 'PREPARE_INGRESS_TAB_DATA';
export const PREPARE_INGRESS_TAB_DATA_REQUEST =
  'PREPARE_INGRESS_TAB_DATA_REQUEST';
export const PREPARE_INGRESS_TAB_DATA_SUCCESS =
  'PREPARE_INGRESS_TAB_DATA_SUCCESS';
export const PREPARE_INGRESS_TAB_DATA_ERROR = 'PREPARE_INGRESS_TAB_DATA_ERROR';

export const CATALOG_LOAD_INDEX_REQUEST = 'CATALOG_LOAD_INDEX_REQUEST';
export const CATALOG_LOAD_INDEX_SUCCESS = 'CATALOG_LOAD_INDEX_SUCCESS';
export const CATALOG_LOAD_INDEX_ERROR = 'CATALOG_LOAD_INDEX_ERROR';

export const CLUSTER_LOAD_APP_README_REQUEST =
  'CLUSTER_LOAD_APP_README_REQUEST';
export const CLUSTER_LOAD_APP_README_SUCCESS =
  'CLUSTER_LOAD_APP_README_SUCCESS';
export const CLUSTER_LOAD_APP_README_ERROR = 'CLUSTER_LOAD_APP_README_ERROR';

export const CLUSTER_CREATE_APP_CONFIG_REQUEST =
  'CLUSTER_CREATE_APP_CONFIG_REQUEST';
export const CLUSTER_CREATE_APP_CONFIG_SUCCESS =
  'CLUSTER_CREATE_APP_CONFIG_SUCCESS';
export const CLUSTER_CREATE_APP_CONFIG_ERROR =
  'CLUSTER_CREATE_APP_CONFIG_ERROR';

export const CLUSTER_UPDATE_APP_CONFIG_REQUEST =
  'CLUSTER_UPDATE_APP_CONFIG_REQUEST';
export const CLUSTER_UPDATE_APP_CONFIG_SUCCESS =
  'CLUSTER_UPDATE_APP_CONFIG_SUCCESS';
export const CLUSTER_UPDATE_APP_CONFIG_ERROR =
  'CLUSTER_UPDATE_APP_CONFIG_ERROR';

export const CLUSTER_DELETE_APP_CONFIG_REQUEST =
  'CLUSTER_DELETE_APP_CONFIG_REQUEST';
export const CLUSTER_DELETE_APP_CONFIG_SUCCESS =
  'CLUSTER_DELETE_APP_CONFIG_SUCCESS';
export const CLUSTER_DELETE_APP_CONFIG_ERROR =
  'CLUSTER_UPDATE_APP_CONFIG_ERROR';

export const CLUSTER_CREATE_APP_SECRET_REQUEST =
  'CLUSTER_CREATE_APP_SECRET_REQUEST';
export const CLUSTER_CREATE_APP_SECRET_SUCCESS =
  'CLUSTER_CREATE_APP_SECRET_SUCCESS';
export const CLUSTER_CREATE_APP_SECRET_ERROR =
  'CLUSTER_CREATE_APP_SECRET_ERROR';

export const CLUSTER_UPDATE_APP_SECRET_REQUEST =
  'CLUSTER_UPDATE_APP_SECRET_REQUEST';
export const CLUSTER_UPDATE_APP_SECRET_SUCCESS =
  'CLUSTER_UPDATE_APP_SECRET_SUCCESS';
export const CLUSTER_UPDATE_APP_SECRET_ERROR =
  'CLUSTER_UPDATE_APP_SECRET_ERROR';

export const CLUSTER_DELETE_APP_SECRET_REQUEST =
  'CLUSTER_DELETE_APP_SECRET_REQUEST';
export const CLUSTER_DELETE_APP_SECRET_SUCCESS =
  'CLUSTER_DELETE_APP_SECRET_SUCCESS';
export const CLUSTER_DELETE_APP_SECRET_ERROR =
  'CLUSTER_UPDATE_APP_SECRET_ERROR';
