export const UPDATE_CLUSTER_LABELS = 'UPDATE_CLUSTER_LABELS';
export const UPDATE_CLUSTER_LABELS_REQUEST = 'UPDATE_CLUSTER_LABELS_REQUEST';
export const UPDATE_CLUSTER_LABELS_SUCCESS = 'UPDATE_CLUSTER_LABELS_SUCCESS';
export const UPDATE_CLUSTER_LABELS_ERROR = 'UPDATE_CLUSTER_LABELS_ERROR';
