name: happa-service-type-migration
namespace: giantswarm

userID: 1000
groupID: 1000

image:
  registry: quay.io
  repository: giantswarm/k8s-migrator
  tag: latest

resources:
  limits:
    cpu: 50m
    memory: 75Mi
  requests:
    cpu: 50m
    memory: 75Mi
