export const RELEASES_LOAD = 'RELEASES_LOAD';
export const RELEASES_LOAD_REQUEST = 'RELEASES_LOAD_REQUEST';
export const RELEASES_LOAD_SUCCESS = 'RELEASES_LOAD_SUCCESS';
export const RELEASES_LOAD_ERROR = 'RELEASES_LOAD_ERROR';
