{{- if not .Values.happa.letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: happa-certs
  namespace: giantswarm
  labels:
    app: happa
data:
  tls.crt: {{ .Values.certificate.monitoring.crtPem | quote }}
  tls.key: {{ .Values.certificate.monitoring.keyPem | quote }}
{{- end }}
