apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: happa-certs-secret
  namespace: giantswarm
  labels:
    app: happa
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
