{{- if not .Values.happa.letsencrypt }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: happa-certs
  namespace: giantswarm
  labels:
    app: happa
data:
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.keyPemB64 | quote }}
{{- end }}
