{{- if not .Values.Installation.V1.GiantSwarm.Happa.Letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: happa-certs
  namespace: {{ .Values.namespace }}
  labels:
    app: happa
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
{{- end }}
