apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    app: {{ tpl .Values.resource.default.name  . }}
data:
  passage-endpoint: {{ .Values.Installation.V1.GiantSwarm.Passage.Address }}
  api-endpoint: {{ .Values.Installation.V1.GiantSwarm.API.Address }}
  ingress-base-domain:
    {
      { .Values.Installation.V1.Guest.Kubernetes.IngressController.BaseDomain },
    }
  aws-capabilities-json: '{{ .Values.Installation.V1.Provider.AWS.EC2.Instance.Capabilities | toJson }}'
  azure-capabilities-json: '{{ .Values.Installation.V1.Provider.Azure.VM.VmSize.Capabilities | toJson }}'
