apiVersion: v1
kind: ConfigMap
metadata:
  name: happa-configmap
  namespace: giantswarm
  labels:
    app: happa
data:
  config.yaml: |
    passage-endpoint: {{ .Values.passage.address }}
    api-endpoint: {{ .Values.api.address }}
    mapi-endpoint: {{ .Values.happaapi.address }}
    audience: {{ .Values.api.address }}
    mapi-audience: {{ .Values.oidc.issuerAddress }}
    ingress-base-domain: {{ .Values.guestCluster.base }}
    installation-name: {{ .Values.managementCluster.name }}
    {{- if eq .Values.managementCluster.provider.kind "aws" }}
    aws-capabilities-json: '{{ .Values.aws.instance.capabilities | toJson }}'
    {{- end }}
    {{- if eq .Values.managementCluster.provider.kind "azure" }}
    azure-capabilities-json: '{{ .Values.azure.vm.vmSize.capabilities | toJson }}'
    {{- end }}
    default-request-timeout-seconds: '10'
    provider: {{ .Values.managementCluster.provider.kind }}
    mapi-auth-redirect-url: {{ .Values.happa.address }}
    mapi-auth-admin-group: {{ .Values.kubernetes.auth.controlPlaneAdminTargetGroup }}
    sentry-dsn: https://e2d0c60518114bf1b920f3cac4ee3f26@o346224.ingest.sentry.io/5739870
    sentry-environment: {{ .Values.managementCluster.name }}
    sentry-release-version: {{ .Values.image.tag }}
    sentry-debug: 'FALSE'
    sentry-sample-rate: '0.5'

    # Enables real user monitoring (RUM)
    enable-rum: 'TRUE'

    # Feature flags
    feature-mapi-auth: {{ .Values.happa.featureFlags.mapiAuth | quote | upper }}
    feature-mapi-clusters: {{ .Values.happa.featureFlags.mapiClusters | quote | upper }}

    {{- if and (eq .Values.managementCluster.customer "giantswarm") (ne .Values.managementCluster.pipeline "testing") }}
    # Shared installations don't get the Monitoring feature
    feature-monitoring: "FALSE"
    {{- else }}
    feature-monitoring: "TRUE"
    {{- end }}
