apiVersion: apps/v1
kind: Deployment
metadata:
  name: happa
  namespace: giantswarm
  labels:
    app: happa
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: happa
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        app: happa
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                    - happa
              topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: happa
        image: {{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
        - name: AWS_CAPABILITIES_JSON
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: aws-capabilities-json
        {{- end }}
        {{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
        - name: AZURE_CAPABILITIES_JSON
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: azure-capabilities-json
        {{- end }}
        - name: PASSAGE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: passage-endpoint
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: api-endpoint
        - name: MAPI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: mapi-endpoint
        - name: AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: audience
        - name: MAPI_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: mapi-audience
        - name: INGRESS_BASE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: ingress-base-domain
        - name: INSTALLATION_NAME
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: installation-name
        - name: DEFAULT_REQUEST_TIMEOUT_SECONDS
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: default-request-timeout-seconds
        - name: PROVIDER
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: provider
        - name: ENABLE_RUM
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: enable-rum
        - name: MAPI_AUTH_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: mapi-auth-redirect-url
        - name: MAPI_AUTH_ADMIN_GROUP
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: mapi-auth-admin-group
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: sentry-dsn
        - name: SENTRY_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: sentry-environment
        - name: SENTRY_RELEASE_VERSION
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: sentry-release-version
        - name: SENTRY_DEBUG
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: sentry-debug
        - name: SENTRY_SAMPLE_RATE
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: sentry-sample-rate
        - name: ENVIRONMENT
          value: kubernetes
        - name: FEATURE_MAPI_AUTH
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: feature-mapi-auth
        - name: FEATURE_MAPI_CLUSTERS
          valueFrom:
            configMapKeyRef:
              name: happa-configmap
              key: feature-mapi-clusters
        - name: FEATURE_MONITORING
        {{- if and (eq .Values.Installation.V1.Customer "giantswarm") (eq .Values.Installation.V1.Infra.TestingEnvironment false) }}
          # Shared installations don't get the Monitoring feature
          value: "FALSE"
        {{- else }}
          value: "TRUE"
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - mountPath: /tmp
          name: nginx-tmpfs
      imagePullSecrets:
      - name: happa-pull-secret
      volumes:
      - name: nginx-tmpfs
        emptyDir:
          medium: Memory
          sizeLimit: 200Mi
