{{- if not .Values.happaapi.letsencrypt }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: happaapi-certs
  namespace: default # default namespace because of kubernetes service
  labels:
    app: happa
data:
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.keyPemB64 | quote }}
{{- end }}
