{{- if not .Values.happaapi.letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: happaapi-certs
  namespace: default
  labels:
    app: happa
data:
  tls.crt: {{ .Values.certificate.monitoring.crtPem | quote }}
  tls.key: {{ .Values.certificate.monitoring.keyPem | quote }}
{{- end }}
