kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  name: {{ tpl .Values.resource.default.name  . }}
spec:
  podSelector:
    matchLabels:
      app: {{ tpl .Values.resource.default.name  . }}
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: {{ .Values.protocol }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
