export const METADATA_UPDATE_SET_TIMER = 'METADATA_UPDATE_SET_TIMER';
export const METADATA_UPDATE_SET_VERSION = 'METADATA_UPDATE_SET_VERSION';
export const METADATA_UPDATE_SET_VERSION_SUCCESS =
  'METADATA_UPDATE_SET_VERSION_SUCCESS';
export const METADATA_UPDATE_START_CHECK = 'METADATA_UPDATE_START_CHECK';
export const METADATA_UPDATE_CHECK = 'METADATA_UPDATE_CHECK';
export const METADATA_UPDATE_SCHEDULE = 'METADATA_UPDATE_SCHEDULE';
export const METADATA_UPDATE_EXECUTE = 'METADATA_UPDATE_EXECUTE';
export const METADATA_UPDATE_EXECUTE_REQUEST =
  'METADATA_UPDATE_EXECUTE_REQUEST';
