name: JS Dependency Audit

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/npm-shrinkwrap.json'
      - '**/yarn.lock'
      - '**/.yarnrc'
      - '**/.yarnrc.yml'
      - '**/pnpm-lock.yaml'
      - '**/pnpm-workspace.yaml'

permissions: {}

jobs:
  audit:
    # TODO: switch ref to @main once the reusable workflow has landed.
    uses: giantswarm/github-workflows/.github/workflows/js-dependency-audit.yaml@add-npm-audit-workflow
    permissions:
      contents: read
      pull-requests: write
